### PR TITLE
Adding/Formatting with `ocamlformat`

### PR DESCRIPTION
**Pull request by rbonichon**
This PR is up for debate but should be applied after #11 or instead of #11 since the first 4 commits are shared

This applies `ocamlformat` to the whole project after adding a dedicated formatting target in the Makefile.

I understand that this may not be the style you want to use, so we can 
- disregard this PR altogether
- agree to use ocamlformat but with a different configuration file (I use the defaults here)
- use the default ocamlformat

The main advantage of using a code formatter is to ~~avoid any further debate on style ;-)~~ have a consistent style throughout the codebase and to possibly ease PR reviews. I understand that these elements may not be on `mlpost`'s list of necessities as of right now, but I do propose to include ocamlformat as code formatter.

### CODE REVIEW

**Comment by rbonichon** [comment]
I've just added the `.git-blame-ignore-revs` file. What kind of test do you have in mind? I'm not sure about how to test against ocamlformat's changes. Regarding the version itself, I guess we could enforce it in the `opam` file, right ?

**Comment by backtracking** [comment]
I will definitely not use `ocamlformat` for my personal code. But I agree that a consistent style is a good idea when collaborating. Since both @bobot and @rbonichon are already in favor of `ocamlformat` why not?
To be clear: unless we set up some github action, I'll simply have to do a systematic `make fmt` before committing, right?

**Comment by rbonichon** [comment]
@backtracking Yes, or even more convenient, you could add a `'before-save-hook` hook in your Emacs configuration. `ocamlformat` actually provides some elisp to do just that.

**Comment by backtracking** [comment]
OK thanks. So I'll merge this PR.

**Comment by backtracking** [comment]
I get this warning:
```
Warning: Version 1.2 of integration with automatic formatters is not
supported until version 1.11 of the dune language.
There are no supported versions of this extension in version 1.1 of the dune
language.
```
Should we switch to dune 2.0?

**Comment by backtracking** [comment]
Note: this PR accidentally reverted my commit regarding dependency over `ppx_bitstring` (used to be `bitstring.ppx`).
Fixed with commit 067d3ed.

**Comment by rbonichon** [comment]
Sorry for the reverted `bitstring` dependency.

I have indeed `dune 1.11.4` in my environment. You appear to have a substantially older dune version and I did not check beforehand...
In your case does `(use fmt 1.1)`. or `(use fmt 1.0)`  in `src/dune-project` remove the warning ?

With dune 2.0, we would not need the `use fmt` expression.

**Comment by backtracking** [comment]
No problem for `bitstring`.

I'm using dune 2.7.1.

Note: If we switch to dune 2.0,  there would be other changes to do, such as `action` in `examples/dune` that is not part of dune anymore.

**Pull request merged**
